#!/usr/bin/env python3
"""
Active runtime parameters for `emerging_cooperation.py`.

Edit the `config` dict directly. Use `seed=None` to disable the fixed seed.
"""

config = {
    "w": 60,
    "h": 60,
    "pred_init": 65,
    "prey_init": 575,
    "pred_energy_init": 1.4,
    "steps": 1000,
    "metab_pred": 0.053,
    "move_cost": 0.008,
    "coop_cost": 0.14,
    "birth_thresh_pred": 4.8,
    "pred_repro_prob": 0.045,
    "pred_max": 800,
    "mut_rate": 0.03,
    "mut_sigma": 0.08,
    "local_birth_r": 1,
    "hunt_r": 1,
    "hunt_rule": "energy_threshold_gate",
    "p0": 0.60,
    "hunter_pool_r": 1,
    "equal_split_rewards": True,
    "enable_plasticity": False,
    "plasticity_strength": 0.25,
    "plasticity_ratio_setpoint": 4.0,
    "plasticity_ratio_scale": 2.0,
    "log_reward_split": False,
    "log_energy_budget": False,
    "energy_log_every": 1,
    "energy_invariant_tol": 1e-6,
    "prey_move_prob": 0.30,
    "prey_repro_prob": 0.078,
    "prey_max": 3200,
    "prey_energy_mean": 1.1,
    "prey_energy_sigma": 0.25,
    "prey_energy_min": 0.10,
    "prey_metab": 0.05,
    "prey_move_cost": 0.01,
    "prey_birth_thresh": 2.0,
    "prey_birth_split": 0.42,
    "prey_bite_size": 0.24,
    "grass_init": 0.8,
    "grass_max": 3.0,
    "grass_regrowth": 0.055,
    "animate": False,
    "animate_simple_grid": False,
    "anim_steps": 500,
    "anim_interval_ms": 40,
    "plot_macro_energy_flows": True,
    "live_render_pygame": True,
    "live_render_fps": 30,
    "live_render_cell_size": 14,
    "clust_r": 2,
    "pred_size": 70,
    "pred_edge_linewidth": 1.2,
    "prey_density_alpha": 0.35,
    "cluster_alpha": 1.0,
    "seed": 0,
    "restart_on_extinction": False,
    "max_restarts": 60,
}
